apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/boonchris/argocd-demo.git
    targetRevision: HEAD
    path: keycloak
    helm:
      # values: |
      #   namespaceOverride: keycloak
      #   ingress:
      #     enabled: true
      #     ingressClassName: nginx
      #     hostname: keycloak.example
      #     path: /
      valueFiles:
      - values.yaml
  
  destination:    
    server: https://kubernetes.default.svc
    namespace: keycloak

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
