apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: default

  sources:
  - repoURL: registry-1.docker.io/bitnamicharts
    chart: keycloak
    targetRevision: 24.4.13    
    helm:
      valueFiles:
      - $values/keycloak/values.yaml
  - repoURL: https://github.com/boonchris/argocd-demo.git
    targetRevision: HEAD
    ref: values
  
  destination:    
    server: https://kubernetes.default.svc
    namespace: keycloak

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true